version: '3.8'

services:
  # 1. LE CERVEAU (Backend Python)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: verifdoc_backend
    restart: always
    env_file: .env.prod
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/verifdoc
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - db

  # 2. LE VISAGE (Frontend React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: verifdoc_frontend
    restart: always
    ports:
      - "80:80"

  # 3. LA MÉMOIRE (Base de données)
  db:
    image: postgres:15-alpine
    container_name: verifdoc_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=verifdoc
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # 4. LE PORTIER (HTTPS Automatique)
  # caddy:
  #   image: caddy:2-alpine
  #   ... (Configuration Caddy à venir)

volumes:
  postgres_data:
